# -*- coding: utf-8 -*-
"""App code made.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzsGhiV3oQFRJyUN7rMXYbuYRCRQ5G3v
"""



# prompt: def greet_user():
#     # Ask the user for their name
#     name = input("What is your name? ")
#     # Respond with a greeting
#     print(f"Hello, {name}!")
#     # Ask the user how they're doing
#     mood = input(f"How are you today, {name}? ")
#     # Respond based on their input
#     if mood.lower() in ['good', 'great', 'fine', 'well']:
#         print("That's awesome! Glad to hear you're doing well!")
#     else:
#         print("I hope your day gets better soon!")
# # Start the conversation
# if __name__ == "__main__":
#     greet_user()

def greet_user():
    # Ask the user for their name
    name = input("What is your name? ")
    # Respond with a greeting
    print(f"Hello, {name}!")
    # Ask the user how they're doing
    mood = input(f"How are you today, {name}? ")
    # Respond based on their input
    if mood.lower() in ['good', 'great', 'fine', 'well']:
        print("That's awesome! Glad to hear you're doing well!")
    else:
        print("I hope your day gets better soon!")
# Start the conversation
if __name__ == "__main__":
    greet_user()